services:
  postgres:
    container_name: postgres-sql-waq
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: security_clone
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - security-clone
    restart: unless-stopped

networks:
  security-clone:
    driver: bridge

volumes:
  postgres:
    driver: local