spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp_clone
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSALDialect
    flyway:
      enabled: false
